[package]
name = "symfonysecret"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.4"
clap = { version = "4.4.6", features = ["derive"] }
reqwest = "0.11.22"
ring = "0.17.0"
tokio = {version = "1.32.0", features = ["full"] }
url = "2.4.1"
percent-encoding = "2"
html2text = "0.6.0"
